vim.o.swapfile = false
vim.o.laststatus = 2
vim.o.number = true
vim.o.relativenumber = true
vim.o.tabstop = 4
vim.o.softtabstop = 4
vim.o.shiftwidth = 4
vim.o.hidden = true
vim.o.colorcolumn = "120"
vim.o.mouse = "nv"
vim.o.path = vim.o.path .. "**"
vim.o.clipboard = vim.o.clipboard .. "unnamedplus"
vim.o.backup = false
vim.o.writebackup = false
vim.o.wb = false
vim.o.showmode = false
vim.o.cursorline = true
vim.o.incsearch = true
vim.o.splitright = true
vim.o.splitbelow = true
vim.o.expandtab = true
vim.o.guifont = "JetBrainsMono Nerd Font Mono:h18"
vim.o.completeopt = "menuone,noselect"
vim.o.termguicolors = true
