require "plugins.install"
require "plugins.lsp_config"
require "plugins.structlog"
require "plugins.file_manager"
require "plugins.telescope"
require 'plugins.tree_sitter'
require 'plugins.theme'
require 'plugins.wakatime'
require 'plugins.neogit'
require 'plugins.bufferline'
require 'plugins.dap'
require 'plugins.dotnet'
require 'plugins.lualine'
require 'plugins.opencode'
