vim.pack.add {
    "https://github.com/willothy/nvim-cokeline",
    'https://github.com/mfussenegger/nvim-dap',
    'https://github.com/nvim-neotest/nvim-nio',
    'https://github.com/rcarriga/nvim-dap-ui',
    'https://github.com/GustavEikaas/easy-dotnet.nvim',
    'https://github.com/nvim-tree/nvim-web-devicons',
    { src = 'https://github.com/nvim-tree/nvim-tree.lua' },
    'https://github.com/neovim/nvim-lspconfig',
    'https://github.com/mason-org/mason.nvim',
    'https://github.com/xzbdmw/colorful-menu.nvim',
    'https://github.com/rachartier/tiny-inline-diagnostic.nvim',
    { src = 'https://github.com/saghen/blink.cmp',       version = 'v1' },
    'https://github.com/mason-org/mason-lspconfig.nvim',
    'https://github.com/rachartier/tiny-inline-diagnostic.nvim',
    'https://github.com/nvim-lualine/lualine.nvim',
    'https://github.com/linrongbin16/lsp-progress.nvim',
    'https://github.com/NeogitOrg/neogit',
    "https://github.com/Tastyep/structlog.nvim",
    'https://github.com/nvim-lua/plenary.nvim',
    'https://github.com/nvim-telescope/telescope.nvim',
    'https://github.com/nvim-treesitter/nvim-treesitter',
    'https://github.com/wakatime/vim-wakatime',
    'https://github.com/nvimdev/lspsaga.nvim',
    'https://github.com/rachartier/tiny-code-action.nvim',
    'https://github.com/EdenEast/nightfox.nvim',
    'https://github.com/sudo-tee/opencode.nvim',
    'https://github.com/folke/which-key.nvim'
}
